version: '3.0'

services:
  api_backend:
    container_name: api_backend
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    networks:
      - api_backend
    restart: always
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/www/api_backend/docker-volumes/postgres
    networks:
      - api_backend
    restart: unless-stopped
#  pgadmin4:
#      container_name: pgadmin4
#      image: dpage/pgadmin4
#      ports:
#        - 5050:80
#      environment:
#        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#        - PGADMIN_DEFAULT_PASSWORD=pgadmin4
#        - PGADMIN_CONFIG_SERVER_MODE=False
#      depends_on:
#        - postgres
#      volumes:
#        - pgadmin:/var/www/api_backend/docker-volumes/pgadmin
#      networks:
#        - api_backend
#      restart: unless-stopped

networks:
  api_backend:
    driver: bridge

volumes:
  postgres:
#  pgadmin: