name: Pupils Tracker Frontend Actions
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
      services:
        postgres:
          image
      steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'
        - name: Install dependencies
            run: npm ci
        - name: Build project
          run: npm run start:prod --if-present
